Fix AUR/Homebrew update
spicetify/spicetify-cli pull request #2058
Opened 2022-12-18 22:23 UTC by itsmeow

For some reason this refuses to redirect/proxy from the old URL on my side so I'm just going to change it here. I made some server changes that broke some of my webserver stuff, sorry about that.

2022-12-21 15:53 UTC, theRealPadster requested changes

2022-12-21 15:53 UTC, theRealPadster commented on .github/workflows/build.yml
>        - name: Update Homebrew/AUR
```suggestion
      - name: Update AUR package
```
Since we're going to do the homebrew one with a separate action.

2022-12-23 13:22 UTC, ririxidev approved these changes

2022-12-23 13:52 UTC, theRealPadster approved these changes

2022-12-23 14:12 UTC, merged