feat(github/actions) Add homebrew release step
spicetify/spicetify-cli pull request #2060
Opened 2022-12-21 16:47 UTC by theRealPadster

I don't know if this works at all. Please someone look at it.

2022-12-21 16:49 UTC, theRealPadster commented
Stupid conventional commits still hate me even when I add them. smh.

2022-12-23 13:00 UTC, itsmeow commented
Try running it on a fork with a different target repo

2022-12-23 20:47 UTC, theRealPadster commented
> Try running it on a fork with a different target repo

Tested on a fork of the [cli](https://github.com/theRealPadster/spicetify-cli) repo and the [tap](https://github.com/theRealPadster/spicetify-homebrew-tap) repo. It looks like we need to add an access token to the cli repo if we don't have one (I can't see them), since the default `GITHUB_TOKEN` doesn't work between repos. 

[This](https://github.com/theRealPadster/spicetify-homebrew-tap/commit/287fb66b6db239175f2f72970eef6ce56604f2c9) is the commit it made. Looks like it generates the formula from scratch, based on the action. For some reason the indentation for the install step is messed up though. Maybe from the workflow?

2022-12-24 23:01 UTC, ririxidev requested changes

2022-12-24 23:01 UTC, ririxidev commented on .github/workflows/build.yml
> +          base-branch: master
```suggestion
          base-branch: main
```

2022-12-27 15:05 UTC, ririxidev approved these changes

2022-12-27 15:08 UTC, itsmeow requested changes

2022-12-27 15:08 UTC, itsmeow commented on .github/workflows/build.yml
> +          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
this will break soon (march 2023). It needs to use output environment files

2022-12-27 15:08 UTC, kyrie25 approved these changes

2022-12-27 15:16 UTC, itsmeow approved these changes

2022-12-27 15:17 UTC, merged