fix(lyrics-plus): copy converted Japanese lyrics
spicetify/spicetify-cli pull request #2075
Opened 2022-12-29 12:21 UTC by kyrie25

lol
![image](https://user-images.githubusercontent.com/77577746/209950492-a0daa344-ef6b-4eea-8c83-9043f3def4f7.png)

2022-12-29 12:49 UTC, ririxidev approved these changes

2022-12-30 03:38 UTC, afonsojramos approved these changes

2022-12-30 03:39 UTC, afonsojramos requested changes
I think we could extract this code to a function to remove its duplication, no?

2022-12-30 03:40 UTC, kyrie25 commented
> I think we could extract this code to a function to remove its duplication, no?

Yeah I suppose so, will look into it later.

2022-12-30 10:21 UTC, afonsojramos approved these changes

2022-12-30 10:21 UTC, merged