placeholder for pull request
spicetify/spicetify-cli pull request #2086
Opened 2023-01-06 00:40 UTC by vegerot

2023-01-06 00:42 UTC, CharlieS1103 approved these changes
Seems good to me

2023-01-06 01:26 UTC, theRealPadster requested changes
If you're specifying each OS, then you need to mention Linux as well. I'd recommend just saying "ctrl/cmd + shift + I"

2023-01-06 05:20 UTC, vegerot commented
> If you're specifying each OS, then you need to mention Linux as well. I'd recommend just saying "ctrl/cmd + shift + I"

but it's not shift, it's option (alt)

`ctrl/cmd + shift/option + I` sounds weird xD

2023-01-06 13:48 UTC, theRealPadster commented
> but it's not shift, it's option (alt)
> 
> `ctrl/cmd + shift/option + I` sounds weird xD

Ahh that's why I could never get the shortcut to work on macos 😂 then I'd just add a "/Linux" to your "(Windows)"

2023-01-09 02:44 UTC, theRealPadster requested changes
I think this addresses all the feedback.

2023-01-09 02:44 UTC, theRealPadster commented on spicetify.go
> +                    Hit Ctrl + Shift + I (Windows) or Cmd + Option + I (macOS) in the client to start using.
```suggestion
                    Press Ctrl + Shift + I (Windows/Linux) or Cmd + Option + I (macOS) in the Spotify client to start using.
```

2023-01-09 19:31 UTC, vegerot commented
@theRealPadster I don't have permission to merge this PR

2023-01-09 19:44 UTC, merged