feat(lyrics-plus): support for enhanced LRC
spicetify/spicetify-cli pull request #2180
Opened 2023-03-01 06:25 UTC by kyrie25

Track link for cross-referrence: [505 - Arctic Monkeys](https://open.spotify.com/track/0BxE4FqsDD1Ot4YuBXwAPp?si=b513cf4d07f6469d)

![Spotify_eydpCXIjBF](https://user-images.githubusercontent.com/77577746/222061093-2b13935a-82a4-4502-b726-5e6d35f32480.gif)

2023-03-01 11:52 UTC, kyrie25 commented
Some more stuff

![image](https://user-images.githubusercontent.com/77577746/222131820-401c01f1-9222-49f8-839e-d37349a40558.png)
![image](https://user-images.githubusercontent.com/77577746/222131799-6fc88721-dc89-4ab5-b786-ebcd0e14f84b.png)

2023-03-02 13:32 UTC, kyrie25 commented
Should be stable now.

2023-03-18 19:26 UTC, rxri requested changes

2023-03-18 19:26 UTC, rxri commented on CustomApps/lyrics-plus/Settings.js
> +			disabled: count === 0
```suggestion
			disabled: !count
```

2023-03-18 19:26 UTC, rxri commented on CustomApps/lyrics-plus/Settings.js
> +	const text = count > 0 ? "Clear cached lyrics" : "No cached lyrics";
```suggestion
	const text = !count ? "Clear cached lyrics" : "No cached lyrics";
```

2023-03-18 19:26 UTC, rxri commented on CustomApps/lyrics-plus/Utils.js
> +		} else return timestamp.toString();
```suggestion
		if (isNaN(timestamp)) return timestamp.toString();
		let minutes = Math.trunc(timestamp / 60000),
			seconds = ((timestamp - minutes * 60000) / 1000).toFixed(2);

		if (minutes < 10) minutes = "0" + minutes;
		if (seconds < 10) seconds = "0" + seconds;

		return `${minutes}:${seconds}`;
```

2023-03-18 19:26 UTC, rxri commented on CustomApps/lyrics-plus/Utils.js
> +			} else return timestamp.toString();
```suggestion
		if (isNaN(timestamp)) return timestamp.toString();
		let minutes = Math.trunc(timestamp / 60000),
			seconds = ((timestamp - minutes * 60000) / 1000).toFixed(2);
		if (minutes < 10) minutes = "0" + minutes;
		if (seconds < 10) seconds = "0" + seconds;
		return `${minutes}:${seconds}`;
```

2023-03-18 19:26 UTC, rxri commented on CustomApps/lyrics-plus/Utils.js
> +			let karaokeLine = [];
```suggestion
			const karaokeLine = [];
```

2023-03-19 13:47 UTC, rxri approved these changes

2023-03-29 14:59 UTC, theRealPadster approved these changes
LGTM

2023-03-29 15:24 UTC, merged