feat(lyrics-plus): chinese characters convertion
spicetify/spicetify-cli pull request #2203
Opened 2023-03-18 10:19 UTC by Deskehs

Add support for Chinese Language conversion without interrupting Japanese Language conversion. Closes #2174 

https://user-images.githubusercontent.com/124361319/226099583-afd336ab-6338-4d8d-bc64-39816acb6be9.mp4

2023-03-18 19:35 UTC, rxri requested changes

2023-03-18 19:35 UTC, rxri commented on CustomApps/lyrics-plus/index.js
> +			if (language != "ja") return;
```suggestion
			if (language !== "ja") return;
```

2023-03-18 19:35 UTC, rxri commented on CustomApps/lyrics-plus/index.js
> +			if (!language.includes("zh") || (language == "zh-hans" && params[0] == "t") || (language == "zh-hant" && params[0] == "cn")) return;
```suggestion
			if (!language.includes("zh") || (language === "zh-hans" && params[0] === "t") || (language === "zh-hant" && params[0] === "cn")) return;
```

2023-03-18 19:35 UTC, rxri commented on CustomApps/lyrics-plus/Translator.js
>  			//Waiting for JSDeliver to load Kuroshiro and Kuromoji
```suggestion
			// Waiting for JSDeliver to load Kuroshiro, Kuromoji and OpenCC
```

2023-03-24 07:22 UTC, rxri requested changes

2023-03-24 07:22 UTC, rxri commented on CustomApps/lyrics-plus/Settings.js
> +					info: "Same as above but with Traditional/Simplified Chinese. This setting is in percentage.",
Don't use "Same as above [...]" wording

2023-03-25 09:18 UTC, Deskehs commented on CustomApps/lyrics-plus/Settings.js
> +					info: "Same as above but with Traditional/Simplified Chinese. This setting is in percentage.",
Done.

2023-03-25 12:35 UTC, rxri approved these changes

2023-03-25 12:36 UTC, kyrie25 approved these changes

2023-03-25 13:32 UTC, merged

2024-01-22 09:14 UTC, Aurora-Simba commented
I am currently facing some problems in the lastest veision. When the subtitles are in traditional Chinese, the display mode is set to simplified Chinese, but the lyrics are still in traditional Chinese. Convert is already on, and the setting for traditional Chinese detection is 5%