feat(src): dedicated theme user.js
spicetify/spicetify-cli pull request #2256
Opened 2023-04-10 01:52 UTC by ohitstom

## This PR allows theme creators to implement extensions for their theme within the themes folder. 

This removes the need for every theme to have its own install script in which it needs to move js files and modify the config, this PR will not affect older themes that do not have a user.js as it will simply skip my implemented stuff.

##
![image](https://user-images.githubusercontent.com/22730962/230808976-34983c0a-befa-490e-b6dc-3fd6ceb292fa.png)

![image](https://user-images.githubusercontent.com/22730962/230809001-a4ed2cbc-3e8c-4bfc-b8be-9c67003f9a07.png)

![image](https://user-images.githubusercontent.com/22730962/230808960-13472fa2-b91d-42c5-b700-d685eaa17066.png)

2023-04-10 01:55 UTC, ohitstom commented
This is my first time using GO or really learning how Spicetify does its logic for config related stuff, go easy on me.
I havent found any technical issues with my approach to it, however there could be lots of redundancy or 'better' ways of doing stuff. 

Please let me know.

2023-04-11 14:09 UTC, rxri requested changes

2023-04-11 14:09 UTC, rxri commented on spicetify.go
> +					return "", errors.New("Invalid Flag\nAvailable Flags: -e, -c, -a, -s")
Use `utils.Fatal`

2023-04-11 14:09 UTC, rxri commented on src/cmd/apply.go
> +		utils.PrintSuccess("Custom JS is updated")
`Custom JS` but `dedicated theme script` *?* Decide on description what it's supposed to do. Either choose that it's javascript related to themes or custom js file that has nothing to do with themes

2023-04-11 14:19 UTC, rxri requested changes

2023-04-11 14:19 UTC, rxri commented on src/cmd/apply.go
> +		utils.PrintSuccess("Custom JS is updated")
```suggestion
		utils.PrintSuccess("Theme's javascript is updated")
```

2023-04-11 14:19 UTC, rxri commented on src/cmd/apply.go
> +func pushThemeExtension() {
```suggestion
func pushThemeJavascript() {
```

2023-04-11 14:19 UTC, rxri commented on src/cmd/apply.go
> +		pushThemeExtension()
```suggestion
		pushThemeJavascript()
```

2023-04-11 14:19 UTC, rxri commented on src/cmd/apply.go
> +		pushThemeExtension()
```suggestion
		pushThemeJavascript()
```

2023-04-11 14:19 UTC, rxri commented on src/cmd/watch.go
> +				pushThemeExtension()
```suggestion
				pushThemeJavascript()
```

2023-04-11 14:19 UTC, rxri commented on src/cmd/watch.go
> +				utils.PrintSuccess(utils.PrependTime("Custom JS is updated"))
```suggestion
				utils.PrintSuccess(utils.PrependTime("Theme's javascript is updated"))
```

2023-04-11 14:37 UTC, ohitstom commented
Sorry i didn't know you could batch do these changes ^

2023-04-11 19:01 UTC, rxri approved these changes

2023-04-11 22:55 UTC, kyrie25 approved these changes

2023-04-11 23:57 UTC, merged