feat(lyrics-plus): hangul transliteration support
spicetify/spicetify-cli pull request #2293
Opened 2023-04-25 10:17 UTC by ohitstom

This PR adds transliteration options for korean synced lyrics (hangul) to roman letters (romaja/latin script), resolves #2247.

![image](https://user-images.githubusercontent.com/22730962/234247333-6c5301f3-eb74-456c-85b0-53719647de36.png)
![image](https://user-images.githubusercontent.com/22730962/234247367-fa1dcae3-f3ac-4a1a-9b44-cfdf1fb1b95d.png)

2023-04-25 10:21 UTC, ohitstom commented
These are my current possible concerns for code, i believe they should be correct but i dont entirely understand their function and may need correcting/given a proper explanation.

![image](https://user-images.githubusercontent.com/22730962/234248392-a98d6d59-d865-4b37-9807-bbc1f3c7d6af.png)
![image](https://user-images.githubusercontent.com/22730962/234248398-b35a5638-c87c-4d0e-845b-e641e9c8d1f1.png)

2023-04-25 14:33 UTC, kyrie25 requested changes

2023-04-25 14:33 UTC, kyrie25 commented on CustomApps/lyrics-plus/index.js
> +		].map(params => {
Created array has no value and is not needed.
```suggestion
		].forEach(params => {
```

2023-04-25 14:33 UTC, kyrie25 commented on CustomApps/lyrics-plus/Translator.js
> +		if (target == "hangul") {
```suggestion
		if (target === "hangul") {
```

2023-04-25 14:40 UTC, kyrie25 requested changes

2023-04-26 07:15 UTC, ohitstom commented
closed and reopened cause flow wouldnt initialize

2023-04-26 07:21 UTC, kyrie25 requested changes

2023-04-26 07:21 UTC, kyrie25 commented on CustomApps/lyrics-plus/Utils.js
> +			}
Place these above the other conditions so it doesn't execute unnecessary code.

2023-04-26 07:30 UTC, kyrie25 requested changes
Last one.

2023-04-26 07:30 UTC, kyrie25 commented on CustomApps/lyrics-plus/Translator.js
> +		}
```suggestion
		if (target === "hangul") return text;
		return Aromanize.hangulToLatin(text, "rr-translit");
```

2023-04-26 07:36 UTC, kyrie25 approved these changes

2023-04-27 12:16 UTC, rxri requested changes
I don't think it's necessary to load every library when it's not needed, shouldn't we load them accordingly to what user enables?

2023-04-28 12:19 UTC, Tetrax-10 commented
> I don't think it's necessary to load every library when it's not needed, shouldn't we load them accordingly to what user enables?

#2122 in this PR the translation is only enabled only when the user clicks a translation option. The same you can just check what translation option is selected and then load that minified Library.

2023-04-28 21:55 UTC, rxri approved these changes
after some discussion I came to conclusion that it can be done later on

2023-04-28 21:56 UTC, merged