fix(exp-features): save config after reset
spicetify/spicetify-cli pull request #2295
Opened 2023-04-26 15:17 UTC by kyrie25

Save configuration properly instead of temporary changing value in features map. This resolves the issue of configuration resolving to local values instead of remote after a reset.

2023-04-27 12:18 UTC, rxri requested changes

2023-04-27 12:18 UTC, rxri commented on jsHelper/expFeatures.js
> +				}
```suggestion
				row.style.display = row.textContent.trim().toLowerCase().includes(query) || row.id.toLowerCase().includes(query) ? "flex" : "none"
```

2023-04-28 12:09 UTC, Tetrax-10 commented
Yup this one works fine. The problem occurs when resetting the exp features.

Like for some people Library x was enabled remotely. But when resetting the exp features the lib x was applied but then after a refresh the UI reverts to old UI. After this the resting works fine.

2023-04-28 16:37 UTC, rxri approved these changes

2023-05-01 15:34 UTC, kyrie25 commented
For some reason a small amount of people are getting old versions of `xpui` so added a fallback method just in case it is an old version or if the hook breaks in the future.
![IZP3hrsdmv](https://user-images.githubusercontent.com/77577746/235478752-ff5d0b05-3722-4c05-aa72-5c5694619d32.gif)

2023-05-02 16:05 UTC, theRealPadster approved these changes

2023-05-02 16:27 UTC, merged