feat: Improved Netease lyrics algorithm
spicetify/spicetify-cli pull request #2310
Opened 2023-05-01 14:09 UTC by Lseoksee

1. The existing Netease lyrics were too inaccurate. In addition to comparing album names, this commit adds a method of comparing the length of the song in milliseconds (milliseconds are specified as ±500 milliseconds because there is a slight error), if either of these conditions is not met, it returns no lyrics (because otherwise useless lyrics will be returned)
2. The return value "纯音乐, 请欣赏" for lyrics Netease doesn't seem to be the track Instrumental. Sometimes when listening to local music or songs by indie artists, Instrumental is displayed. Therefore, it was modified to be displayed as no lyrics.
3. Fixed an issue where, when viewing the lyrics of Netease" in popupLyrics, the song would be displayed as prelude if there was a blank during the lyrics. the problem did not exist in lyrics-plus, so please leave an answer if this feature is intended.

2023-05-01 14:37 UTC, kyrie25 commented
> 1. The existing Netease lyrics were too inaccurate. In addition to comparing album names, this commit adds a method of comparing the length of the song in milliseconds (milliseconds are specified as ±500 milliseconds because there is a slight error)

I think the error margin can be increased, as there can be instances where you'd need to increase up to 2000-3000ms at most for offset. I'm assuming that should be safe, though can you give an opinion on that suggestion or test it out?

2023-05-01 15:25 UTC, Lseoksee commented
> I think the error margin can be increased, as there can be instances where you'd need to change up to 2000-3000ms at most for offset. I'm assuming that should be safe, though can you give an opinion on that suggestion or test it out?

Tests have shown that when offset is over 1000, a small number of songs bring lyrics incorrectly. So I think 1000 is the maximum limit also, when I tested offset at 500, I rarely went out of the offset range, so I think it would be good to set it to 1000.

2023-05-01 15:35 UTC, kyrie25 commented
> Tests have shown that when offset is over 1000, a small number of songs bring lyrics incorrectly. So I think 1000 is the maximum limit also, when I tested offset at 500, I rarely went out of the offset range, so I think it would be good to set it to 1000.

Sounds good to me.

2023-05-01 19:48 UTC, rxri requested changes
Please also run prettier

2023-05-01 23:16 UTC, Lseoksee commented
> Please also run prettier

Why does the "prettier" error occur?

2023-05-02 14:38 UTC, Lseoksee commented
@kyrie25  @rxri   `Fatal: could not read Username for 'https://github.com ': No Such device or address` error occurs during prettier operation, how do I resolve it?

2023-05-02 14:50 UTC, rxri commented
Run prettier in your vscode with `.prettierrc` found in our repo to prettify commands. Don't mind Action throwing this error because it's trying to push commit that has it prettified but it can't

2023-05-03 01:44 UTC, Lseoksee commented
I solved it!

2023-05-03 02:47 UTC, rxri approved these changes

2023-05-03 03:36 UTC, kyrie25 requested changes

2023-05-03 03:36 UTC, kyrie25 commented on CustomApps/lyrics-plus/ProviderNetease.js
> +			val => Utils.capitalize(val.album.name) === album || (info.duration + 1000 > val.duration && info.duration - 1000 < val.duration)
This should be valid.
```suggestion
			val => Utils.capitalize(val.album.name) === album || Math.abs(info.duration - val.duration) < 1000
```

2023-05-03 03:36 UTC, kyrie25 commented on Extensions/popupLyrics.js
> +				val => LyricUtils.capitalize(val.album.name) === album || (info.duration + 1000 > val.duration && info.duration - 1000 < val.duration)
```suggestion
				val => LyricUtils.capitalize(val.album.name) === album || Math.abs(info.duration - val.duration) < 1000
```

2023-05-03 05:07 UTC, kyrie25 approved these changes

2023-05-03 05:08 UTC, merged