feat(lyrics-plus): playbar button
spicetify/spicetify-cli pull request #2327
Opened 2023-05-05 19:53 UTC by ohitstom

resolves #2314.

![image](https://user-images.githubusercontent.com/22730962/236556525-40c90a25-4070-4906-b734-447e8c3c8eec.png)
![image](https://user-images.githubusercontent.com/22730962/236556376-496d2806-e177-4a37-a813-7ffb0054d705.png)

2023-05-05 23:21 UTC, ohitstom commented
> use event listener on localstorage to detect changes and run functions based on value

2023-05-06 13:24 UTC, kyrie25 requested changes

2023-05-06 13:24 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +	</svg>`,
```suggestion
	const button = new Spicetify.Playbar.Button(
		"Lyrics Plus",
		"lyrics",
```

2023-05-06 13:24 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +			}
```suggestion
			Spicetify.Platform.History.location.pathname !== "/lyrics-plus" ? Spicetify.Platform.History.push("/lyrics-plus") : Spicetify.Platform.History.goBack()
```

2023-05-06 13:24 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +	}
```suggestion
	if (initialValue === "true") setPlaybarButton();
```

2023-05-06 13:24 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +		if (event.detail.name === "playbar-button") {
```suggestion
		if (event.detail?.name === "playbar-button") {
```

2023-05-06 13:24 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +		style.classList.add("lyrics-plus:visual:playbar-button");
Create the stylesheet outside the scope of this function. Then on each of the create and remove button function you'll only need to run `document.head.appendChild(style);` and `style.remove()` subsequently,

2023-05-06 13:24 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +		const style = document.head.querySelector(".lyrics-plus\\:visual\\:playbar-button");
Ditto.

2023-05-06 13:37 UTC, ohitstom commented on CustomApps/lyrics-plus/PlaybarButton.js
> +	</svg>`,
i disagree
![image](https://user-images.githubusercontent.com/22730962/236627634-2ebf8eb5-28bd-4b58-8273-3a18d6952f9f.png)

2023-05-06 14:37 UTC, kyrie25 requested changes

2023-05-06 14:37 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +	});
```suggestion
	Spicetify.Platform.History.listen(location => button.active = location.pathname === "/lyrics-plus");
```

2023-05-06 15:04 UTC, kyrie25 requested changes

2023-05-06 15:04 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +		},
```suggestion
		() => Spicetify.Platform.History.location.pathname !== "/lyrics-plus" ? Spicetify.Platform.History.push("/lyrics-plus") : Spicetify.Platform.History.goBack(),
```

2023-05-06 15:04 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +	style.innerHTML = css;
```suggestion
	style.innerHTML = `
		.main-nowPlayingBar-lyricsButton { 
			display: none !important; 
		}
		li[data-id="/lyrics-plus"] {
			display: none;
		}
	`;
```

2023-05-06 15:04 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +		}
```suggestion
		if (event.detail?.name === "playbar-button") event.detail.value ? setPlaybarButton() : removePlaybarButton();
```

2023-05-06 15:04 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +	if (Spicetify.Platform.History.location.pathname === "/lyrics-plus") button.active = true;
```suggestion
	button.active = Spicetify.Platform.History.location.pathname === "/lyrics-plus";
```

2023-05-06 15:07 UTC, kyrie25 commented on CustomApps/lyrics-plus/PlaybarButton.js
> +	if (Spicetify.Platform.History.location.pathname === "/lyrics-plus") button.active = true;
Actually, just merge this onto the constructor above.

2023-05-06 15:31 UTC, kyrie25 approved these changes

2023-05-06 15:38 UTC, kyrie25 requested changes
Last one, wording is kinda weird

2023-05-06 15:38 UTC, kyrie25 commented on CustomApps/lyrics-plus/Settings.js
> +					info: "Replace Spotify's lyrics button for one that opens lyrics-plus.",
```suggestion
					info: "Replace Spotify's lyrics button Lyrics Plus'",
```

2023-05-06 16:46 UTC, rxri approved these changes

2023-05-06 23:48 UTC, kyrie25 approved these changes

2023-05-06 23:49 UTC, merged