fix(lyrics-plus): absolute positioning on main view
spicetify/spicetify-cli pull request #2402
Opened 2023-06-10 17:31 UTC by ohitstom

before + after.

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/4f4a1901-6679-479f-8021-51839e809571)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/0625bfcf-e752-4f88-85d6-e9bf8a979efb)

removes scrollbar etc, please test before accepting however i did go over everything i could think of (fullscreen, no blur/overlay, no lyrics, different text sizes, compact vs non compact etc.)

2023-06-14 05:41 UTC, ohitstom commented
@kyrie25 @rxri

2023-06-14 11:14 UTC, kyrie25 requested changes

2023-06-14 11:14 UTC, kyrie25 commented on CustomApps/lyrics-plus/style.css
> +	height: 10vh;
Doesn't look quite right when the track is instrumental, should leave it as-is or find another solution.
![image](https://github.com/spicetify/spicetify-cli/assets/77577746/9837e921-bb29-4870-a24e-125b6f84db6a)
![image](https://github.com/spicetify/spicetify-cli/assets/77577746/4ff7f271-a8e1-4239-a4ef-8787a19fe23a)

2023-06-14 11:39 UTC, kyrie25 commented on CustomApps/lyrics-plus/style.css
> +	height: 10vh;
Doesn't look quite right when the track is instrumenta.
![image](https://github.com/spicetify/spicetify-cli/assets/77577746/9837e921-bb29-4870-a24e-125b6f84db6a)

```suggestion
	height: calc(50vh - 12px - 90px - var(--lyrics-font-size));
}

.lyrics-lyricsContainer-UnsyncedLyricsPage:has(.lyrics-lyricsContainer-LyricsLine:nth-child(3)) .lyrics-lyricsContainer-LyricsUnsyncedPadding {
	height: 10vh;
}
```

2023-06-14 11:55 UTC, kyrie25 requested changes
Address comment.

2023-06-14 23:21 UTC, kyrie25 approved these changes

2023-06-17 14:05 UTC, theRealPadster approved these changes

2023-06-17 14:19 UTC, rxri approved these changes

2023-06-17 14:19 UTC, merged