feat(upgrade): verify backup status
spicetify/spicetify-cli pull request #2448
Opened 2023-06-29 14:30 UTC by ohitstom

This PR will ensure the user is told the correct commands to run, the issue this solves is:

 whenever a users Spotify has updated BEFORE they then run `spicetify upgrade`, the backups are mismatched, they are then told to run `spicetify restore backup apply` which will plonk their old backup files into their new spotify installation causing issues. This PR checks for this and tells them to just run `spicetify backup apply`.

2023-06-30 03:20 UTC, kyrie25 approved these changes

2023-07-03 12:06 UTC, rxri requested changes

2023-07-03 12:06 UTC, rxri commented on src/cmd/upgrade.go
> +	}
```suggestion
	cmd := []string{"spicetify", "backup", "apply"}
	if !backStat.IsOutdated() {
		cmd = append(cmd[:1], append([]string{"restore"}, cmd[1:]...)...)
	}
	
	utils.PrintInfo(`Please run "` + strings.Join(cmd, " ") + `" to receive new features and bug fixes`)
```

2023-07-03 12:06 UTC, rxri commented on src/cmd/upgrade.go
>  	"runtime"
```suggestion
	"runtime"
	"strings"
```

2023-07-03 14:35 UTC, rxri commented on src/cmd/upgrade.go
> +
```suggestion

```

2023-07-03 14:54 UTC, rxri approved these changes

2023-07-03 14:54 UTC, merged