Add Chip ReactComponent
spicetify/spicetify-cli pull request #2640
Opened 2023-11-09 06:50 UTC by duffey

It can be used like:

```jsx
<Spicetify.ReactComponent.Chip
    className="encore-dark-theme"
    isUsingKeyboard={false}
    onClick={null}
    size={true}
    iconTrailing={() => (<MyIcon />)}>hello</Spicetify.ReactComponent.Chip>
```

Please let me know if I need to modify anything else to make it easier to use or otherwise.

2023-11-09 15:39 UTC, ohitstom commented
Any chance you could also provide a non-jsx code example and screenshots of potential usage.
Until docs are updated we point developers to pull requests for example usage, so it would be helpful!

2023-11-10 13:25 UTC, duffey commented
I made some examples here: https://github.com/duffey/spicetify-chip-examples

2023-11-10 14:38 UTC, duffey commented
I understand now you meant creating the components in pure JS, so I will try to do that.

2023-11-10 14:51 UTC, ohitstom commented
> I understand now you meant creating the components in pure JS, so I will try to do that.

you can just modify your original pr message to include this stuff 👍

2023-11-10 15:08 UTC, duffey commented
> > I understand now you meant creating the components in pure JS, so I will try to do that.
> 
> you can just modify your original pr message to include this stuff 👍

OK!

2023-11-12 00:32 UTC, rxri requested changes

2023-11-12 00:32 UTC, rxri commented on jsHelper/spicetifyWrapper.js
> +			Chip: modules.find(m => m?.render?.toString().includes("invertedDark")),
```suggestion
			Chip: modules.find(m => m?.render?.toString().includes("invertedDark") && m?.render?.toString().includes("isUsingKeyboard")),
```

2023-11-14 18:58 UTC, rxri approved these changes

2023-11-17 12:01 UTC, afonsojramos commented
Oh nice! Thanks @duffey

2023-11-17 12:01 UTC, afonsojramos approved these changes

2023-11-17 12:01 UTC, merged