refactor(install/windows): rewrite script
spicetify/spicetify-cli pull request #2663
Opened 2023-11-15 21:32 UTC by SunsetTechuila

test carefully and feel free to suggest changes

2023-11-17 12:03 UTC, afonsojramos commented
I'm very wary of changing our install scripts at this point in time, because they currently work well, and we'll probably move off of install scripts for v3. If I have access to a windows machine in the next week I'll try to test it out!

2023-11-24 15:59 UTC, afonsojramos commented
We should probably also update the documentation for the installation then, no? 
And also get the `.sh` installation to also query for Marketplace installation, way better implementation than simply giving two scripts directly for sure.

2023-11-24 16:01 UTC, SunsetTechuila commented
> We should probably also update the documentation for the installation then, no?
yes

2023-11-24 16:03 UTC, SunsetTechuila commented
> And also get the .sh installation to also query for Marketplace installation,

i don't know bash

2023-12-05 11:57 UTC, SunsetTechuila commented
> And also get the .sh installation to also query for Marketplace installation,
@afonsojramos done

2023-12-05 12:09 UTC, afonsojramos commented
@SunsetTechuila is this expected behaviour?
<img width="844" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/19473034/13947fe7-4c7b-40bd-aa60-9b8da7fd1fc4">

2023-12-05 12:11 UTC, afonsojramos commented
Shell one looks good tho!

2023-12-05 12:17 UTC, SunsetTechuila commented
> is this expected behaviour?

no, have fixed it

2023-12-09 17:27 UTC, afonsojramos commented
@SunsetTechuila getting this at the marketplace section 
<img width="838" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/19473034/325002be-daf6-4c36-af90-a8c0daf8a881">

2023-12-10 18:21 UTC, SunsetTechuila commented
@afonsojramos fixed

![image](https://github.com/spicetify/spicetify-cli/assets/115353812/cba2018b-0ba2-4a23-810d-fefbcc97a893)

2023-12-18 10:56 UTC, afonsojramos requested changes
@SunsetTechuila The only thing that I don't quite like is that most messages show up as "verbose". That doesn't make that much sense if the "Success" afterwards doesn't... Let's keep them as normal messages, like we've had.

<img width="976" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/19473034/7621f535-94ac-4c36-86de-75cd80e5839b">

PS: This was ran in a windows pc that doesn't have Spotify installed.

2023-12-18 12:55 UTC, SunsetTechuila commented
@afonsojramos is it better now?

![image](https://github.com/spicetify/spicetify-cli/assets/115353812/f50c9c99-8fa5-42e1-ac01-9a33bf2ba8a0)

2023-12-19 14:24 UTC, afonsojramos approved these changes
I feel like it is perfect now, thanks @SunsetTechuila! Requesting some other eyes as well

2023-12-22 19:49 UTC, rxri requested changes
- The install.log is missing, and it was really useful feature, please bring it back
- Colors are not really nice compared to the older script. Personally, I would switch to the old ones
- It would be nice to highlight the `spicetify-h` and change the message containing it because it says `[...] to get started`, but `-h` just shows help message so it isn't really clear
- Also it seems like marketplace script has problem with detecting if spicetify is already applied?
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/9e0419a8-d156-486d-917f-3ff3d986e2ce)

2023-12-22 19:53 UTC, SunsetTechuila commented
> The install.log is missing, and it was really useful feature, please bring it back

I've never seen anyone use it

2023-12-22 19:55 UTC, rxri commented
> > The install.log is missing, and it was really useful feature, please bring it back
> 
> I've never seen anyone use it

v3 will definitely use it and that's how we will ask people to send install logs. Removing it now, isn't the best idea then

2023-12-22 19:58 UTC, SunsetTechuila commented
> v3 will definitely use it 

> [we'll probably move off of install scripts for v3](https://github.com/spicetify/spicetify-cli/pull/2663#issuecomment-1816270321)

![image](https://github.com/spicetify/spicetify-cli/assets/115353812/bd67de71-073b-4979-bba3-d39ba57dff78)

ummm?

2023-12-22 19:59 UTC, rxri commented
Yes, but the installer will generate the log xd

2023-12-22 20:01 UTC, SunsetTechuila commented
and how this makes removing logging that no one uses a bad idea?

2023-12-22 20:02 UTC, SunsetTechuila commented
![image](https://github.com/spicetify/spicetify-cli/assets/115353812/ae08f169-6360-431c-899a-33667b2fcb06)

4 results. support server exists since 2021

2023-12-22 20:12 UTC, SunsetTechuila commented
> and change the message containing it

to what exactly

2023-12-22 20:23 UTC, SunsetTechuila commented
> Colors are not really nice compared to the older script. Personally, I would switch to the old ones

I used cyan so that the info lines about current actions would not merge with the prompts
Do you really insist on making them white?

2023-12-27 15:20 UTC, rxri requested changes

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +    Write-Host -Object 'Adding Spicetify to your PATH if needed...' -NoNewline
```suggestion
    Write-Host -Object 'Making spicetify available in the PATH...' -NoNewline

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +  Write-Host -Object 'Starting the Spicetify Marketplace installation script..'
```suggestion
  Write-Host -Object 'Starting the spicetify Marketplace installation script..'

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +  Write-Host -Object 'Spicetify Marketplace installation aborted' -ForegroundColor 'Yellow'
```suggestion
  Write-Host -Object 'spicetify Marketplace installation aborted' -ForegroundColor 'Yellow'

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +    Write-Host -Object 'Spicetify installation aborted' -ForegroundColor 'Yellow'
```suggestion
    Write-Host -Object 'spicetify installation aborted' -ForegroundColor 'Yellow'

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +    Write-Host -Object 'Spicetify was successfully installed!' -ForegroundColor 'Green'
```suggestion
    Write-Host -Object 'spicetify was successfully installed!' -ForegroundColor 'Green'

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +    Write-Host -Object 'Extracting Spicetify...' -NoNewline
```suggestion
    Write-Host -Object 'Extracting spicetify...' -NoNewline

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +    Write-Host -Object 'Installing Spicetify...'
```suggestion
    Write-Host -Object 'Installing spicetify...'

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +    Write-Host -Object "Downloading Spicetify v$targetVersion..." -NoNewline
```suggestion
    Write-Host -Object "Downloading spicetify v$targetVersion..." -NoNewline

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +      Write-Host -Object 'Fetching the latest Spicetify version...' -NoNewline
```suggestion
      Write-Host -Object 'Fetching the latest spicetify version...' -NoNewline

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +        Write-Warning -Message "You have spicefied an invalid Spicetify version: $v `nThe version must be in the following format: 1.2.3"
```suggestion
        Write-Warning -Message "You have spicefied an invalid spicetify version: $v `nThe version must be in the following format: 1.2.3"

```

2023-12-27 15:20 UTC, rxri commented on install.ps1
> +      Write-Host -Object 'Moving your old Spicetify folder...' -NoNewline
```suggestion
      Write-Host -Object 'Moving the old spicetify folder...' -NoNewline

```

2023-12-27 15:20 UTC, rxri commented on install.sh
> +	echo "Spicetify Marketplace installation aborted"
```suggestion
	echo "spicetify Marketplace installation aborted"
```

2023-12-27 15:20 UTC, rxri commented on install.sh
> +read -p "Do you want to install Spicetify Marketplace? (Y/n) " choice
```suggestion
read -p "Do you want to install spicetify Marketplace? (Y/n) " choice
```

2023-12-27 15:20 UTC, rxri commented on install.sh
> +echo "Starting the Spicetify Marketplace installation script.."
```suggestion
echo "Starting the spicetify Marketplace installation script.."
```

2023-12-27 15:21 UTC, rxri approved these changes

2023-12-27 15:23 UTC, merged