feat(wrapper): add `Dropdown` ReactComponent
spicetify/spicetify-cli pull request #2709
Opened 2023-12-07 20:05 UTC by SunsetTechuila

tested with spotify v1.2.26 and v1.2.0

2023-12-07 20:11 UTC, SunsetTechuila commented
just realized that this makes very little sense lol

2024-01-11 20:27 UTC, SunsetTechuila commented
just realized that this makes not very little sense lol

2024-01-12 11:20 UTC, rxri requested changes

2024-01-12 11:20 UTC, rxri commented on jsHelper/spicetifyWrapper.js
> +			).find(m => typeof m === "function"),
make it a chunk like `PlaylistMenu` because i'm pretty sure it can cause problems later

2024-01-13 22:48 UTC, rxri approved these changes

2024-01-15 09:53 UTC, afonsojramos approved these changes

2024-01-15 12:38 UTC, merged