fix(new-releases): repair artist list query & removal notification
spicetify/spicetify-cli pull request #2716
Opened 2023-12-10 04:21 UTC by ohitstom

new removal notification example:
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/f0e2990d-f83e-4982-9a49-3974ed96a24b)

2023-12-10 04:23 UTC, ohitstom commented
should i add support for the old cosmo request too? i havent checked if these platform methods are present across all versioning

2023-12-13 06:55 UTC, ohitstom commented
I've formatted so not sure why run is failing

2023-12-22 19:54 UTC, rxri requested changes
Run prettier (with new version, because it uses different style for conditional operator)

2023-12-22 19:55 UTC, ohitstom commented
> Run prettier (with new version, because it uses different style for conditional operator)

I won't be home for the next week, could you make a collaborative commit doing just that please

2023-12-22 20:05 UTC, rxri commented
Just make sure to make the commit before 31.12

2023-12-25 20:03 UTC, ohitstom commented
i assume this is no longer necessary? 

> Just make sure to make the commit before 31.12 if you want this pull request to be included in next update

2023-12-27 15:25 UTC, rxri approved these changes

2023-12-28 03:04 UTC, afonsojramos approved these changes

2023-12-28 03:05 UTC, merged

2024-01-12 20:13 UTC, guiltlab commented
Many thanks for working on this ! I see this has been merged, is it supposed to be working in the latest spicetify version (2.30.0) or is it not implemented yet ? When I try to go to the new-releases panel, the page is always displaying this:

![image](https://github.com/spicetify/spicetify-cli/assets/45518224/a9b9fe6e-6355-4292-84a5-b5c5cb63c40c)

Reloading just takes me to the home page. Thanks in advance !

2024-01-13 03:07 UTC, ohitstom commented
> Many thanks for working on this ! I see this has been merged, is it supposed to be working in the latest spicetify version (2.30.0) or is it not implemented yet ? When I try to go to the new-releases panel, the page is always displaying this:
> 
> ![image](https://github.com/spicetify/spicetify-cli/assets/45518224/a9b9fe6e-6355-4292-84a5-b5c5cb63c40c)
> 
> Reloading just takes me to the home page. Thanks in advance !

can you run spicetify enable-devtools and inspect element and post any errors you see

2024-01-27 14:01 UTC, ohitstom commented
> > > Many thanks for working on this ! I see this has been merged, is it supposed to be working in the latest spicetify version (2.30.0) or is it not implemented yet ? When I try to go to the new-releases panel, the page is always displaying this:
> > > ![image](https://private-user-images.githubusercontent.com/45518224/296354579-a9b9fe6e-6355-4292-84a5-b5c5cb63c40c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTg1MTQsIm5iZiI6MTcwNjM1ODIxNCwicGF0aCI6Ii80NTUxODIyNC8yOTYzNTQ1NzktYTliOWZlNmUtNjM1NS00MjkyLTg0YTUtYjVjNWNiNjNjNDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEyMjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YTI1MzJkZWIxZTZjNjk3MjI1MmViYmMzODJmNjAxODhmZTI3OGYzODJjMDE5YmYzM2MxNDJmYzE3YzQyMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zD5I9dZB93CNTxCZu4jKClUPAectc3r0I28r6wai-PU)
> > > Reloading just takes me to the home page. Thanks in advance !
> > 
> > can you run spicetify enable-devtools and inspect element and post any errors you see and send version information outside of just spice please
> 
> Apologies for the late reply ! 
> 
> EDIT: I found the issue! For some reason, the files in my spicetify were not updated in AppData\Roaming, instead the ones in AppDate\Local were updated and those didn't seem to apply. I added the repo files from the customapps/new-releases to my AppData\Roaming directory, and now it works fine!!
> Thanks for fixing this <3
> 
> <details><summary>Original post</summary>
> 
> What elements should I provide with Inspect element ?
> Spicetify marketplace version: 0.8.6
> This is the code I see on the New Releases button:
> ```
> <li class="main-yourLibraryX-navItem InvalidDropTarget" data-id="/marketplace"><a draggable="false" aria-label="Search" class="link-subtle main-yourLibraryX-navLink" href="/marketplace"><svg role="img" height="24" width="24" aria-hidden="true" class="Svg-sc-ytk21e-0 Svg-img-24-icon home-icon" data-encore-id="icon"><svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 76.465 68.262"><path d="M151.909 72.923v6.5h10.097l8.663 44.567h48.968v-6.5h-43.61l-1.2-6.172h42.974l10.35-33.91h-59.915l-.872-4.485H151.91zm17.59 10.984h49.867l-6.393 20.91h-39.409l-4.064-20.91zm5.626 44.11a6.5 6.5 0 0 0-6.5 6.5 6.5 6.5 0 0 0 6.5 6.501 6.5 6.5 0 0 0 6.5-6.5 6.5 6.5 0 0 0-6.5-6.5zm38.274 0a6.5 6.5 0 0 0-6.5 6.5 6.5 6.5 0 0 0 6.5 6.501 6.5 6.5 0 0 0 6.5-6.5 6.5 6.5 0 0 0-6.5-6.5z" style="fill:currentColor;stroke-width:.264583" transform="translate(-151.909 -72.923)"></path></svg>
> </svg><svg role="img" height="24" width="24" aria-hidden="true" class="Svg-sc-ytk21e-0 Svg-img-24-icon home-active-icon" data-encore-id="icon"><svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 76.465 68.262"><path d="M151.909 72.923v6.5h10.097l8.663 44.567h48.968v-6.5h-43.61l-1.2-6.172h42.974l10.35-33.91h-59.915l-.872-4.485H151.91zm23.216 55.095a6.5 6.5 0 0 0-6.5 6.5 6.5 6.5 0 0 0 6.5 6.5 6.5 6.5 0 0 0 6.5-6.5 6.5 6.5 0 0 0-6.5-6.5zm38.274 0a6.5 6.5 0 0 0-6.5 6.5 6.5 6.5 0 0 0 6.5 6.5 6.5 6.5 0 0 0 6.5-6.5 6.5 6.5 0 0 0-6.5-6.5z" style="fill:currentColor;stroke-width:.264583" transform="translate(-151.909 -72.923)"></path></svg>
> </svg><span data-encore-id="type" class="Type__TypeElement-sc-goli3j-0 TypeElement-balladBold-type">Marketplace</span></a></li>
> ```
> 
> This is the code I see on the new releases errored page:
> 
> ```
> <div class="main-pageErrorTemplate-errorBody"><svg data-encore-id="icon" role="img" aria-hidden="true" viewBox="0 0 24 24" class="Svg-sc-ytk21e-0 Svg-img-icon-medium"><path d="M11 18v-2h2v2h-2zm0-4V6h2v8h-2z"></path><path d="M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM1 12C1 5.925 5.925 1 12 1s11 4.925 11 11-4.925 11-11 11S1 18.075 1 12z"></path></svg><h1>Something went wrong</h1><p>Try reloading the page</p><button data-encore-id="buttonPrimary" class="Button-sc-qlcn5g-0 Button-medium-buttonPrimary-useBrowserDefaultFocusStyle"><span class="ButtonInner-sc-14ud5tc-0 ButtonInner-medium encore-bright-accent-set">RELOAD PAGE</span></button></div>
> ```
> 
> <details>
> <summary>This is what i get in the console when I reload the errored page (it takes me to the spicetify marketplace). Lots of errors so mabe this is the source of the issue ?</summary>
> 
> ![image](https://github.com/spicetify/spicetify-cli/assets/45518224/e3d7b81b-19da-481c-bc13-1a5718fa42a3)
> 
> ```
> index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
> (anonymous) @ index.html:1
> vendor~xpui.js:29 logBetamaxPlaybackError
> vendor~xpui.js:29 eventSender exists
> vendor~xpui.js:29 logBetamaxPlaybackError done
> extension.js:1 Initializing Spicetify Marketplace v0.8.6
> extension.js:1 Loaded Marketplace extension
> adblock.js?time=1706358545313:67 [Adblock] Ads disabled {audio: c, vto: {…}, hpto: G, billboard: E, leaderboard: ie, …}
> adblock.js?time=1706358545313:67 [Adblock] Ads disabled {audio: c, vto: {…}, hpto: G, billboard: E, leaderboard: ie, …}
> vendor~xpui.js:29 
>         
>         
>        POST https://gew1-spclient.spotify.com/remote-config-resolver/v3/configuration 404 (Not Found)
> L @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> Promise.then (async)
> (anonymous) @ vendor~xpui.js:29
> _tick @ vendor~xpui.js:29
> start @ vendor~xpui.js:29
> _sendRetriedRequest @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> Promise.then (async)
> _sendRequest @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> _dispatchFromStore @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> a @ vendor~xpui.js:29
> t @ vendor~xpui.js:29
> postMessage (async)
> c @ vendor~xpui.js:29
> emitAndWait @ vendor~xpui.js:29
> i @ vendor~xpui.js:29
> _dispatchFromStore @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> a @ vendor~xpui.js:29
> t @ vendor~xpui.js:29
> postMessage (async)
> c @ vendor~xpui.js:29
> emit @ vendor~xpui.js:29
> _connectToEndpoints @ vendor~xpui.js:29
> Promise.then (async)
> _performConnect @ vendor~xpui.js:29
> _connect @ vendor~xpui.js:29
> connect @ vendor~xpui.js:29
> create @ vendor~xpui.js:29
> t.createUniversalReporter @ vendor~xpui.js:29
> r @ xpui.js:1
> o @ xpui.js:1
> (anonymous) @ xpui.js:1
> await in (anonymous) (async)
> 63202 @ xpui.js:1
> o @ xpui.js:1
> (anonymous) @ xpui.js:1
> o.O @ xpui.js:1
> (anonymous) @ xpui.js:1
> (anonymous) @ xpui.js:1
> vendor~xpui.js:29 provider:transport resolve error T {url: 'https://gew1-spclient.spotify.com/remote-config-resolver/v3/configuration', status: 404, headers: A, body: {…}, offline: false, …} {}
> f @ vendor~xpui.js:29
> t.<computed> @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> Promise.catch (async)
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> a @ vendor~xpui.js:29
> Promise.then (async)
> c @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> p @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> c @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> c @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> y @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> a @ vendor~xpui.js:29
> Promise.then (async)
> c @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> p @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> _ @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> (anonymous) @ vendor~xpui.js:29
> a @ v [...]