feat: expose `ContextMenu` React component via wrapper
spicetify/spicetify-cli pull request #2796
Opened 2024-02-01 18:59 UTC by SunsetTechuila

tested with spotify 1.2.0, 1.2.5, 1.2.8, 1.2.13, 1.2.17, 1.2.23, 1.2.30

2024-02-01 19:05 UTC, rxri approved these changes

2024-02-01 19:05 UTC, rxri requested changes

2024-02-01 19:05 UTC, rxri commented on jsHelper/spicetifyWrapper.js
> +	const contextMenuChunk = Object.entries(require.m).find(([, value]) => value.toString().includes("toggleContextMenu"));
```suggestion
	const contextMenuChunk = chunks.find(([, value]) => value.toString().includes("toggleContextMenu"));
```

wait for #2792 to be merged and change it

2024-02-01 19:09 UTC, rxri commented
resolve conflicts and it's ready to be accepted

2024-02-01 19:13 UTC, rxri approved these changes

2024-02-02 17:48 UTC, afonsojramos approved these changes

2024-02-02 17:50 UTC, merged