fix(homeConfig): support all versions
spicetify/spicetify-cli pull request #2897
Opened 2024-03-11 18:33 UTC by ohitstom

in reference to [this description](https://github.com/spicetify/spicetify-cli/pull/2888#issue-2177763270)

2024-03-11 19:28 UTC, Delusoire commented
This doesn't allow rearranging Meet DJ and Video Coursed because they're only added later.
![image](https://github.com/spicetify/spicetify-cli/assets/71462480/7283ad1a-98d6-4d43-bd30-bd5cbdcba300)

2024-03-11 19:51 UTC, ohitstom commented
> This doesn't allow rearranging Meet DJ and Video Courses because they're only added later.
> ![image](https://github.com/spicetify/spicetify-cli/assets/71462480/7283ad1a-98d6-4d43-bd30-bd5cbdcba300)
> 

this is still proof of concept and homeconfig has never been able to do that.

this approach is no different to the existing one except it means the Regex can be simpler once I've finished it.

2024-03-11 23:03 UTC, rxri commented
good shit, i tested it but it seems like the javascript side is broken now. When I click `down` or `up`, the whole section goes to bottom or top, it doesn't move one by one basically

2024-03-11 23:08 UTC, ohitstom commented
> good shit, i tested it but it seems like the javascript side is broken now. When I click `down` or `up`, the whole section goes to bottom or top, it doesn't move one by one basically

unless im misunderstanding i believe thats intended, basically stick puts it right at the top, lower puts it right at the bottom, then  up or down will move within either stuck sections or lowered sections - i did however notice that if you make a change, the second you change a page and come back it resets until your reload which it wasnt doing with my graphql approach?

2024-03-11 23:10 UTC, rxri commented
nvm i'm just stupid and it actually stays in the same place for me when i change pages

2024-03-11 23:11 UTC, ohitstom commented
> nvm i'm just stupid and it actually stays in the same place for me when i change pages

🎉 will do some testing on why thats not the case for me, might be user error or my localstorage key is messed up

2024-03-11 23:12 UTC, rxri commented
> thoughts on the menu item issue?

known, we didn't bother troubleshooting it further because it worked before and it broke somewhere idk

2024-03-11 23:14 UTC, ohitstom commented
> > thoughts on the menu item issue?
> 
> known, we didn't bother troubleshooting it further because it worked before and it broke somewhere idk

unfortunate, i had a quick look but the new system looks totally different to me haha
i did however fix the logic as its initial state was bugged (in homev2)

2024-03-11 23:34 UTC, rxri requested changes
make `z-index` on `#spicetify-home-config` very high so it's always on top
run `go fmt .`
run biome plox

2024-03-11 23:54 UTC, ohitstom commented
> make `z-index` on `#spicetify-home-config` very high so it's always on top run `go fmt .` run biome plox

will do

2024-03-12 00:10 UTC, rxri commented
> > make `z-index` on `#spicetify-home-config` very high so it's always on top run `go fmt .` run biome plox
> 
> will do
> 
> edit: what is plox?

https://www.dictionary.com/e/slang/plox/
menu item checkmark will be fixed by https://github.com/spicetify/spicetify-cli/pull/2899

2024-03-12 00:13 UTC, rxri approved these changes

2024-03-12 00:17 UTC, ohitstom commented
> menu item checkmark will be fixed by https://github.com/spicetify/spicetify-cli/pull/2899

feel free to say no but may i request that icons still stay on the right like the account one>
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/ee160c98-b0f2-444b-b650-97324f7eadca)
then if item is enabled it replaces the given icon with a check? i feel like that matches Spotify a little bit more !

2024-03-12 01:25 UTC, rxri commented
The account one is like this because that's common to have icon like this on the right to external link, not on the left

2024-03-12 02:10 UTC, ohitstom commented
> The account one is like this because that's common or let's say "standard" to have icon like this on the right to external link, not on the left

sounds good just my OCD haha :)

2024-03-12 02:59 UTC, afonsojramos approved these changes

2024-03-12 03:00 UTC, afonsojramos commented
Let's gooooo

2024-03-12 11:21 UTC, merged

2024-03-13 19:01 UTC, ohitstom commented
> Can anyone explain what this home config feature actually does?

allows you to re-order cards in the home page